## dummy commit 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mock-ics-service-infra-integration-parent
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: mock-ics-service-infra-integration
  source:
    path: apps-children
    repoURL: https://github.com/shamonshan/mock-ics-service-infra-integration
    targetRevision: HEAD
