# App templates can also be defined as part of the generator's template stanza. Sometimes it is
# useful to do this in order to override the spec.template stanza, and when simple string
# parameterization are insufficient. In the below examples, the generators[].XXX.template is 
# a partial definition, which overrides/patch the default template.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: single-namespace-child-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        - name: app-common-ui
          namespace: app-common-port
          url: https://github.com/shamonshan/mock-ics-service-ui
          imageversion: 1.0.1
          applicationversion: HEAD
          helmvaluespath: values-ui.yaml
        - name: app-common-org
          namespace: app-common-port
          url: https://github.com/shamonshan/mock-ics-service-organization-backend
          imageversion: 1.0.1
          applicationversion: HEAD
          helmvaluespath: values-org.yaml
  template:
    metadata:
      name: '{{.name}}'
      labels:
        name: common-children-apps
    spec:
      project: mock-ics-service-infra-integration
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      sources:
      - repoURL: '{{.url}}'
        targetRevision: '{{.applicationversion}}'
        path: helm
        helm:
          valueFiles:
          - $values/helm-configs/{{.helmvaluespath}}
          parameters:
          - name: "image.tag"
            value: '{{.imageversion}}'
          - name : "env.config.local.data.APP_VERSION"
            value : '{{applicationversion}}'
      - repoURL: 'https://github.com/shamonshan/mock-ics-service-infra-integration'
        targetRevision: HEAD
        ref: values