# App templates can also be defined as part of the generator's template stanza. Sometimes it is
# useful to do this in order to override the spec.template stanza, and when simple string
# parameterization are insufficient. In the below examples, the generators[].XXX.template is 
# a partial definition, which overrides/patch the default template.
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: singlenamespace-children-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
   - matrix:
      generators:
      - git:
          repoURL: https://github.com/shamonshan/mock-ics-service-infra-integration
          revision: HEAD
          files:
          - path: app-configs/release.yaml
      - list:
          elements: []
          elementsYaml: "{{ .configs.commonapps | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
      labels:
        name: singlenamespace-children-apps
    spec:
      project: mock-ics-service-infra-integration
      syncPolicy:
        automated: {}
        syncOptions:
          - ApplyOutOfSyncOnly=true
      destination:
        name: in-cluster
        namespace: '{{.namespace}}'
      sources:
      - repoURL: '{{.url}}'
        targetRevision: '{{.applicationversion}}'
        path: helm
        helm:
          valueFiles:
          - $values/helm-configs/{{.helmvaluesfilepath}}
          parameters:
          - name: "image.tag"
            value: '{{.applicationversion}}'
          - name : "env.appVersion"
            value : '{{.configs.version}}'
      - repoURL: 'https://github.com/shamonshan/mock-ics-service-infra-integration'
        targetRevision: HEAD
        ref: values